-- 코드를 입력하세요
WITH TEMP AS (
    SELECT a.CAR_TYPE, a.DAILY_FEE, b.HISTORY_ID, DATEDIFF(b.END_DATE, b.START_DATE) + 1 AS PERIOD,
    CASE
        WHEN DATEDIFF(b.END_DATE, b.START_DATE) + 1 >= 90 THEN '90일 이상'
        WHEN DATEDIFF(b.END_DATE, b.START_DATE) + 1 >= 30 THEN '30일 이상'
        WHEN DATEDIFF(b.END_DATE, b.START_DATE) + 1 >= 7 THEN '7일 이상'
    ELSE 'NONE' END AS DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_CAR AS a
    RIGHT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS b
    ON a.CAR_ID = b.CAR_ID
    WHERE a.CAR_TYPE = '트럭')
    
# SELECT * FROM TEMP
SELECT t.HISTORY_ID, ROUND(t.DAILY_FEE * t.PERIOD * (100 - IFNULL(c.DISCOUNT_RATE, 0)) / 100) AS FEE
FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS c
RIGHT JOIN TEMP AS t
ON t.CAR_TYPE = c.CAR_TYPE AND t.DURATION_TYPE = c.DURATION_TYPE
ORDER BY FEE DESC, HISTORY_ID DESC
